- name: play level variable
  hosts: local
  connection: local
  vars_files:
  - variable.yaml
  tasks:
  - name: print variable
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}, Duration is: {{ DURATIONS }}"
