- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your name...
    private: false

  - name: password
    prompt: please enter your pasword..
    private: true

  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "Username is: {{ username }}, password is: {{ password }} "